//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleModToolAvalonia.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleModToolAvalonia.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ({0} reference) 的本地化字符串。
        /// </summary>
        public static string a_0__reference {
            get {
                return ResourceManager.GetString("a_0__reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active targets 的本地化字符串。
        /// </summary>
        public static string Active_targets {
            get {
                return ResourceManager.GetString("Active_targets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add empty lines: 的本地化字符串。
        /// </summary>
        public static string Add_empty_lines {
            get {
                return ResourceManager.GetString("Add_empty_lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After local variable declarations 的本地化字符串。
        /// </summary>
        public static string After_local_variable_declarations {
            get {
                return ResourceManager.GetString("After_local_variable_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After switch cases 的本地化字符串。
        /// </summary>
        public static string After_switch_cases {
            get {
                return ResourceManager.GetString("After_switch_cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow leftover data on VM stack 的本地化字符串。
        /// </summary>
        public static string Allow_leftover_data_on_VM_stack {
            get {
                return ResourceManager.GetString("Allow_leftover_data_on_VM_stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow statistics 的本地化字符串。
        /// </summary>
        public static string Allow_statistics {
            get {
                return ResourceManager.GetString("Allow_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always use semicolons 的本地化字符串。
        /// </summary>
        public static string Always_use_semicolons {
            get {
                return ResourceManager.GetString("Always_use_semicolons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Around branch statements 的本地化字符串。
        /// </summary>
        public static string Around_branch_statements {
            get {
                return ResourceManager.GetString("Around_branch_statements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Around function declarations 的本地化字符串。
        /// </summary>
        public static string Around_function_declarations {
            get {
                return ResourceManager.GetString("Around_function_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Around static initialization 的本地化字符串。
        /// </summary>
        public static string Around_static_initialization {
            get {
                return ResourceManager.GetString("Around_static_initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Detect 的本地化字符串。
        /// </summary>
        public static string Auto_Detect {
            get {
                return ResourceManager.GetString("Auto_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically compile and decompile code on lost focus 的本地化字符串。
        /// </summary>
        public static string Automatically_compile_and_decompile {
            get {
                return ResourceManager.GetString("Automatically_compile_and_decompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back image 的本地化字符串。
        /// </summary>
        public static string Back_image {
            get {
                return ResourceManager.GetString("Back_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before switch cases 的本地化字符串。
        /// </summary>
        public static string Before_switch_cases {
            get {
                return ResourceManager.GetString("Before_switch_cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilibili… 的本地化字符串。
        /// </summary>
        public static string BilibiliText {
            get {
                return ResourceManager.GetString("BilibiliText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bounding box mode 的本地化字符串。
        /// </summary>
        public static string Bounding_box_mode {
            get {
                return ResourceManager.GetString("Bounding_box_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bounding size 的本地化字符串。
        /// </summary>
        public static string Bounding_size {
            get {
                return ResourceManager.GetString("Bounding_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Builtin array variable syntax 的本地化字符串。
        /// </summary>
        public static string Builtin_array_variable_syntax {
            get {
                return ResourceManager.GetString("Builtin_array_variable_syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bytecode version 的本地化字符串。
        /// </summary>
        public static string Bytecode_version {
            get {
                return ResourceManager.GetString("Bytecode_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Case sensitive 的本地化字符串。
        /// </summary>
        public static string Case_sensitive {
            get {
                return ResourceManager.GetString("Case_sensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a script to run… 的本地化字符串。
        /// </summary>
        public static string ChooseScriptToRunText {
            get {
                return ResourceManager.GetString("ChooseScriptToRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string CloseFileText {
            get {
                return ResourceManager.GetString("CloseFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Tab 的本地化字符串。
        /// </summary>
        public static string CloseTabText {
            get {
                return ResourceManager.GetString("CloseTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code - {0} 的本地化字符串。
        /// </summary>
        public static string Code____0 {
            get {
                return ResourceManager.GetString("Code____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code locals 的本地化字符串。
        /// </summary>
        public static string Code_locals {
            get {
                return ResourceManager.GetString("Code_locals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code locals - {0} 的本地化字符串。
        /// </summary>
        public static string Code_locals____0 {
            get {
                return ResourceManager.GetString("Code_locals____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collision mask data 的本地化字符串。
        /// </summary>
        public static string Collision_mask_data {
            get {
                return ResourceManager.GetString("Collision_mask_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Collision mask entry) 的本地化字符串。
        /// </summary>
        public static string Collision_mask_entry {
            get {
                return ResourceManager.GetString("Collision_mask_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collision masks 的本地化字符串。
        /// </summary>
        public static string Collision_masks {
            get {
                return ResourceManager.GetString("Collision_masks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color depth 的本地化字符串。
        /// </summary>
        public static string Color_depth {
            get {
                return ResourceManager.GetString("Color_depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile and decompile 的本地化字符串。
        /// </summary>
        public static string Compile_and_decompile {
            get {
                return ResourceManager.GetString("Compile_and_decompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config 的本地化字符串。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constants 的本地化字符串。
        /// </summary>
        public static string Constants {
            get {
                return ResourceManager.GetString("Constants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy name 的本地化字符串。
        /// </summary>
        public static string Copy_name {
            get {
                return ResourceManager.GetString("Copy_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create enum declarations 的本地化字符串。
        /// </summary>
        public static string Create_enum_declarations {
            get {
                return ResourceManager.GetString("Create_enum_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debugger port 的本地化字符串。
        /// </summary>
        public static string Debugger_port {
            get {
                return ResourceManager.GetString("Debugger_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default argument values 的本地化字符串。
        /// </summary>
        public static string Default_argument_values {
            get {
                return ResourceManager.GetString("Default_argument_values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default window size 的本地化字符串。
        /// </summary>
        public static string Default_window_size {
            get {
                return ResourceManager.GetString("Default_window_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default room grid size 的本地化字符串。
        /// </summary>
        public static string DefaultRoomGridSize {
            get {
                return ResourceManager.GetString("DefaultRoomGridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DirectPlay GUID 的本地化字符串。
        /// </summary>
        public static string DirectPlay_GUID {
            get {
                return ResourceManager.GetString("DirectPlay_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable GMS debugger 的本地化字符串。
        /// </summary>
        public static string Disable_GMS_debugger {
            get {
                return ResourceManager.GetString("Disable_GMS_debugger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display name 的本地化字符串。
        /// </summary>
        public static string Display_name {
            get {
                return ResourceManager.GetString("Display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded audio - {0} 的本地化字符串。
        /// </summary>
        public static string Embedded_audio____0 {
            get {
                return ResourceManager.GetString("Embedded_audio____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded image - {0} 的本地化字符串。
        /// </summary>
        public static string Embedded_image____0 {
            get {
                return ResourceManager.GetString("Embedded_image____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded texture 的本地化字符串。
        /// </summary>
        public static string Embedded_texture {
            get {
                return ResourceManager.GetString("Embedded_texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded texture - {0} 的本地化字符串。
        /// </summary>
        public static string Embedded_texture____0 {
            get {
                return ResourceManager.GetString("Embedded_texture____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded textures 的本地化字符串。
        /// </summary>
        public static string Embedded_textures {
            get {
                return ResourceManager.GetString("Embedded_textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable syntax highlighting 的本地化字符串。
        /// </summary>
        public static string Enable_syntax_highlighting {
            get {
                return ResourceManager.GetString("Enable_syntax_highlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable room grid by default 的本地化字符串。
        /// </summary>
        public static string EnableRoomGridByDefault {
            get {
                return ResourceManager.GetString("EnableRoomGridByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entry count 的本地化字符串。
        /// </summary>
        public static string Entry_count {
            get {
                return ResourceManager.GetString("Entry_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enum/macro declarations at top of code 的本地化字符串。
        /// </summary>
        public static string Enum_macro_declarations_at_top_of {
            get {
                return ResourceManager.GetString("Enum_macro_declarations_at_top_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export collision mask data 的本地化字符串。
        /// </summary>
        public static string Export_collision_mask_data {
            get {
                return ResourceManager.GetString("Export_collision_mask_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported Sprite Index 的本地化字符串。
        /// </summary>
        public static string Exported_Sprite_Index {
            get {
                return ResourceManager.GetString("Exported_Sprite_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension - {0}} 的本地化字符串。
        /// </summary>
        public static string Extension____0 {
            get {
                return ResourceManager.GetString("Extension____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileName 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string FileText {
            get {
                return ResourceManager.GetString("FileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by name… 的本地化字符串。
        /// </summary>
        public static string FilterByCodeText {
            get {
                return ResourceManager.GetString("FilterByCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find unused assets 的本地化字符串。
        /// </summary>
        public static string Find_unused_assets {
            get {
                return ResourceManager.GetString("Find_unused_assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flags 的本地化字符串。
        /// </summary>
        public static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow System 的本地化字符串。
        /// </summary>
        public static string Follow_System {
            get {
                return ResourceManager.GetString("Follow_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fonts 的本地化字符串。
        /// </summary>
        public static string Fonts {
            get {
                return ResourceManager.GetString("Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FPS 的本地化字符串。
        /// </summary>
        public static string FPS {
            get {
                return ResourceManager.GetString("FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Time (microseconds) 的本地化字符串。
        /// </summary>
        public static string Frame_Time__microseconds {
            get {
                return ResourceManager.GetString("Frame_Time__microseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency 的本地化字符串。
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Front image 的本地化字符串。
        /// </summary>
        public static string Front_image {
            get {
                return ResourceManager.GetString("Front_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function - {0} 的本地化字符串。
        /// </summary>
        public static string Function____0 {
            get {
                return ResourceManager.GetString("Function____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function classifications 的本地化字符串。
        /// </summary>
        public static string Function_classifications {
            get {
                return ResourceManager.GetString("Function_classifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game GUID 的本地化字符串。
        /// </summary>
        public static string Game_GUID {
            get {
                return ResourceManager.GetString("Game_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game ID 的本地化字符串。
        /// </summary>
        public static string Game_ID {
            get {
                return ResourceManager.GetString("Game_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game object - {0} 的本地化字符串。
        /// </summary>
        public static string Game_object____0 {
            get {
                return ResourceManager.GetString("Game_object____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game End Scripts 的本地化字符串。
        /// </summary>
        public static string GameEndScriptsHeading {
            get {
                return ResourceManager.GetString("GameEndScriptsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General info 的本地化字符串。
        /// </summary>
        public static string General_info {
            get {
                return ResourceManager.GetString("General_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Info 的本地化字符串。
        /// </summary>
        public static string GeneralInfoTabHeading {
            get {
                return ResourceManager.GetString("GeneralInfoTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github… 的本地化字符串。
        /// </summary>
        public static string GithubText {
            get {
                return ResourceManager.GetString("GithubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Init Scripts 的本地化字符串。
        /// </summary>
        public static string GlobalInitScriptsHeading {
            get {
                return ResourceManager.GetString("GlobalInitScriptsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group name 的本地化字符串。
        /// </summary>
        public static string Group_name {
            get {
                return ResourceManager.GetString("Group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, adds an empty line after block-scoped local variable declarations. 的本地化字符串。
        /// </summary>
        public static string If_enabled__adds_an_empty_line_after {
            get {
                return ResourceManager.GetString("If_enabled__adds_an_empty_line_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, adds an empty line after (a chain) of &amp;quot;case&amp;quot; entries in a switch statement. 的本地化字符串。
        /// </summary>
        public static string If_enabled__adds_an_empty_line_after1 {
            get {
                return ResourceManager.GetString("If_enabled__adds_an_empty_line_after1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, adds an empty line before and after branch statements. 的本地化字符串。
        /// </summary>
        public static string If_enabled__adds_an_empty_line_before {
            get {
                return ResourceManager.GetString("If_enabled__adds_an_empty_line_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, adds an empty line before (a chain) of &quot;case&quot; entries in a switch statement. 的本地化字符串。
        /// </summary>
        public static string If_enabled__adds_an_empty_line_before1 {
            get {
                return ResourceManager.GetString("If_enabled__adds_an_empty_line_before1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, adds an empty line before and after a function declaration, even if it is anonymous. 的本地化字符串。
        /// </summary>
        public static string If_enabled__adds_an_empty_line_before2 {
            get {
                return ResourceManager.GetString("If_enabled__adds_an_empty_line_before2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, adds an empty line before and after static initialization, grouping together consecutive statics if possible. 的本地化字符串。
        /// </summary>
        public static string If_enabled__adds_an_empty_line_before3 {
            get {
                return ResourceManager.GetString("If_enabled__adds_an_empty_line_before3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, all statements that can have a semicolon after them will. 的本地化字符串。
        /// </summary>
        public static string If_enabled__all_statements_that_can {
            get {
                return ResourceManager.GetString("If_enabled__all_statements_that_can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, blocks that contain a single line will have its braces removed, where possible. For if/else chains, all blocks must be single lines. 的本地化字符串。
        /// </summary>
        public static string If_enabled__blocks_that_contain_a {
            get {
                return ResourceManager.GetString("If_enabled__blocks_that_contain_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, certain builtin globals (such as &amp;quot;view_xview&amp;quot;), when detected to be used without an array accessor, will be printed as such, rather than using compiler-generated syntax. 的本地化字符串。
        /// </summary>
        public static string If_enabled__certain_builtin_globals {
            get {
                return ResourceManager.GetString("If_enabled__certain_builtin_globals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, certain usages of &amp;quot;else&amp;quot; inside of a loop can be transformed into &amp;quot;continue&amp;quot; statements, which can make code easier to read. This only happens if accuracy can be maintained. 的本地化字符串。
        /// </summary>
        public static string If_enabled__certain_usages_of__quot {
            get {
                return ResourceManager.GetString("If_enabled__certain_usages_of__quot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, color constants can be formatted in the #RRGGBB hex format. 的本地化字符串。
        /// </summary>
        public static string If_enabled__color_constants_can_be {
            get {
                return ResourceManager.GetString("If_enabled__color_constants_can_be", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, compiler-generated code and logic for try/catch/finally statements is rewritten to (attempt to) look like the original code. 的本地化字符串。
        /// </summary>
        public static string If_enabled__compiler_generated_code {
            get {
                return ResourceManager.GetString("If_enabled__compiler_generated_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, data left over on the VM stack will be treated as a warning rather than an error. 的本地化字符串。
        /// </summary>
        public static string If_enabled__data_left_over_on_the {
            get {
                return ResourceManager.GetString("If_enabled__data_left_over_on_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, enum declarations identified during decompilation will always be printed to decompiled output. 的本地化字符串。
        /// </summary>
        public static string If_enabled__enum_declarations_identified {
            get {
                return ResourceManager.GetString("If_enabled__enum_declarations_identified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, enums and macros will appear at the start (top) of decompiled output, rather than at the end (bottom). 的本地化字符串。
        /// </summary>
        public static string If_enabled__enums_and_macros_will {
            get {
                return ResourceManager.GetString("If_enabled__enums_and_macros_will", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, local variable declarations will be placed according to their scopes, which are detected based on usage in the code. 的本地化字符串。
        /// </summary>
        public static string If_enabled__local_variable_declarations {
            get {
                return ResourceManager.GetString("If_enabled__local_variable_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, syntax for default named function arguments will be used. Compiler-generated if statements are transformed to do this, maintaining accuracy. 的本地化字符串。
        /// </summary>
        public static string If_enabled__syntax_for_default_named {
            get {
                return ResourceManager.GetString("If_enabled__syntax_for_default_named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, the curly braces used to open a block will be placed on the same line as the statement it belongs to, rather than placing the brace on its own line. 的本地化字符串。
        /// </summary>
        public static string If_enabled__the_curly_braces_used {
            get {
                return ResourceManager.GetString("If_enabled__the_curly_braces_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, warnings generated during decompilation will be printed as comments. 的本地化字符串。
        /// </summary>
        public static string If_enabled__warnings_generated_during {
            get {
                return ResourceManager.GetString("If_enabled__warnings_generated_during", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import collision mask data 的本地化字符串。
        /// </summary>
        public static string Import_collision_mask_data {
            get {
                return ResourceManager.GetString("Import_collision_mask_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent string: 的本地化字符串。
        /// </summary>
        public static string Indent_string {
            get {
                return ResourceManager.GetString("Indent_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inner Script 的本地化字符串。
        /// </summary>
        public static string InnerScriptText {
            get {
                return ResourceManager.GetString("InnerScriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance type 的本地化字符串。
        /// </summary>
        public static string Instance_type {
            get {
                return ResourceManager.GetString("Instance_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is special type 的本地化字符串。
        /// </summary>
        public static string Is_special_type {
            get {
                return ResourceManager.GetString("Is_special_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items/frames per tile 的本地化字符串。
        /// </summary>
        public static string Items_frames_per_tile {
            get {
                return ResourceManager.GetString("Items_frames_per_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🌏Language (Restart to apply) 的本地化字符串。
        /// </summary>
        public static string Language__Restart_to_apply {
            get {
                return ResourceManager.GetString("Language__Restart_to_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language count 的本地化字符串。
        /// </summary>
        public static string Language_count {
            get {
                return ResourceManager.GetString("Language_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last object ID 的本地化字符串。
        /// </summary>
        public static string Last_object_ID {
            get {
                return ResourceManager.GetString("Last_object_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last tile ID 的本地化字符串。
        /// </summary>
        public static string Last_tile_ID {
            get {
                return ResourceManager.GetString("Last_tile_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License CRC32 的本地化字符串。
        /// </summary>
        public static string License_CRC32 {
            get {
                return ResourceManager.GetString("License_CRC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License MD5 的本地化字符串。
        /// </summary>
        public static string License_MD5 {
            get {
                return ResourceManager.GetString("License_MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List 的本地化字符串。
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load alpha 的本地化字符串。
        /// </summary>
        public static string Load_alpha {
            get {
                return ResourceManager.GetString("Load_alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load image 的本地化字符串。
        /// </summary>
        public static string Load_image {
            get {
                return ResourceManager.GetString("Load_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Margin Left/Right/Bottom/Top 的本地化字符串。
        /// </summary>
        public static string Margin_Left_Right_Bottom_Top {
            get {
                return ResourceManager.GetString("Margin_Left_Right_Bottom_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mask 的本地化字符串。
        /// </summary>
        public static string Mask {
            get {
                return ResourceManager.GetString("Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moments 的本地化字符串。
        /// </summary>
        public static string Moments {
            get {
                return ResourceManager.GetString("Moments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name string ID 的本地化字符串。
        /// </summary>
        public static string Name_string_ID {
            get {
                return ResourceManager.GetString("Name_string_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Named instance ID prefix: 的本地化字符串。
        /// </summary>
        public static string Named_instance_ID_prefix {
            get {
                return ResourceManager.GetString("Named_instance_ID_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string NewFileText {
            get {
                return ResourceManager.GetString("NewFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open block braces on same line 的本地化字符串。
        /// </summary>
        public static string Open_block_braces_on_same_line {
            get {
                return ResourceManager.GetString("Open_block_braces_on_same_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open in new tab 的本地化字符串。
        /// </summary>
        public static string Open_in_new_tab {
            get {
                return ResourceManager.GetString("Open_in_new_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string OpenFileText {
            get {
                return ResourceManager.GetString("OpenFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open new resource after create it 的本地化字符串。
        /// </summary>
        public static string OpenNewResourceAfterCreatingIt {
            get {
                return ResourceManager.GetString("OpenNewResourceAfterCreatingIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Origin X/Y 的本地化字符串。
        /// </summary>
        public static string Origin_X_Y {
            get {
                return ResourceManager.GetString("Origin_X_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Border X 的本地化字符串。
        /// </summary>
        public static string Output_Border_X {
            get {
                return ResourceManager.GetString("Output_Border_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Border Y 的本地化字符串。
        /// </summary>
        public static string Output_Border_Y {
            get {
                return ResourceManager.GetString("Output_Border_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent 的本地化字符串。
        /// </summary>
        public static string ParentCode {
            get {
                return ResourceManager.GetString("ParentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Particle system - {0} 的本地化字符串。
        /// </summary>
        public static string Particle_system____0 {
            get {
                return ResourceManager.GetString("Particle_system____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Particle system emitter - {0} 的本地化字符串。
        /// </summary>
        public static string Particle_system_emitter____0 {
            get {
                return ResourceManager.GetString("Particle_system_emitter____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform cleanups: 的本地化字符串。
        /// </summary>
        public static string Perform_cleanups {
            get {
                return ResourceManager.GetString("Perform_cleanups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback speed 的本地化字符串。
        /// </summary>
        public static string Playback_speed {
            get {
                return ResourceManager.GetString("Playback_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback speed type 的本地化字符串。
        /// </summary>
        public static string Playback_speed_type {
            get {
                return ResourceManager.GetString("Playback_speed_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prefix used for named instance IDs when found by decompiler, and for compilation. Change this value if it conflicts with variable names. 的本地化字符串。
        /// </summary>
        public static string Prefix_used_for_named_instance_IDs {
            get {
                return ResourceManager.GetString("Prefix_used_for_named_instance_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preload 的本地化字符串。
        /// </summary>
        public static string Preload {
            get {
                return ResourceManager.GetString("Preload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print warnings 的本地化字符串。
        /// </summary>
        public static string Print_warnings {
            get {
                return ResourceManager.GetString("Print_warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ Group… 的本地化字符串。
        /// </summary>
        public static string QQGroupText {
            get {
                return ResourceManager.GetString("QQGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string QuitText {
            get {
                return ResourceManager.GetString("QuitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 use regular expression  的本地化字符串。
        /// </summary>
        public static string Regular_search {
            get {
                return ResourceManager.GetString("Regular_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove block braces if single line 的本地化字符串。
        /// </summary>
        public static string Remove_block_braces_if_single_line {
            get {
                return ResourceManager.GetString("Remove_block_braces_if_single_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution 的本地化字符串。
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Room 的本地化字符串。
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Room - {0} 的本地化字符串。
        /// </summary>
        public static string Room____0 {
            get {
                return ResourceManager.GetString("Room____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Room order 的本地化字符串。
        /// </summary>
        public static string Room_order {
            get {
                return ResourceManager.GetString("Room_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rooms 的本地化字符串。
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Script 的本地化字符串。
        /// </summary>
        public static string Run_Script {
            get {
                return ResourceManager.GetString("Run_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save audio 的本地化字符串。
        /// </summary>
        public static string Save_audio {
            get {
                return ResourceManager.GetString("Save_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save before closing? 的本地化字符串。
        /// </summary>
        public static string Save_before_closing {
            get {
                return ResourceManager.GetString("Save_before_closing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save before creating? 的本地化字符串。
        /// </summary>
        public static string Save_before_creating {
            get {
                return ResourceManager.GetString("Save_before_creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save before opening? 的本地化字符串。
        /// </summary>
        public static string Save_before_opening {
            get {
                return ResourceManager.GetString("Save_before_opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save datafile 的本地化字符串。
        /// </summary>
        public static string Save_datafile {
            get {
                return ResourceManager.GetString("Save_datafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save image 的本地化字符串。
        /// </summary>
        public static string Save_image {
            get {
                return ResourceManager.GetString("Save_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveFileText {
            get {
                return ResourceManager.GetString("SaveFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving... 的本地化字符串。
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scale 的本地化字符串。
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scope local variable declarations 的本地化字符串。
        /// </summary>
        public static string Scope_local_variable_declarations {
            get {
                return ResourceManager.GetString("Scope_local_variable_declarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script 的本地化字符串。
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Execution 的本地化字符串。
        /// </summary>
        public static string Script_Execution {
            get {
                return ResourceManager.GetString("Script_Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script 的本地化字符串。
        /// </summary>
        public static string ScriptText {
            get {
                return ResourceManager.GetString("ScriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search in Assembly 的本地化字符串。
        /// </summary>
        public static string Search_in_Assembly {
            get {
                return ResourceManager.GetString("Search_in_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Code 的本地化字符串。
        /// </summary>
        public static string SearchCodeText {
            get {
                return ResourceManager.GetString("SearchCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search In Code 的本地化字符串。
        /// </summary>
        public static string SearchInCodeHeading {
            get {
                return ResourceManager.GetString("SearchInCodeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select specific cleanup operations for the decompiler to perform. Disabling these may make code more ugly or &amp;quot;incorrect,&amp;quot; but can show underlying logic. 的本地化字符串。
        /// </summary>
        public static string Select_specific_cleanup_operations {
            get {
                return ResourceManager.GetString("Select_specific_cleanup_operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select specific syntax to add empty lines before, after, or around. 的本地化字符串。
        /// </summary>
        public static string Select_specific_syntax_to_add_empty {
            get {
                return ResourceManager.GetString("Select_specific_syntax_to_add_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Separation mask type 的本地化字符串。
        /// </summary>
        public static string Separation_mask_type {
            get {
                return ResourceManager.GetString("Separation_mask_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsHeading {
            get {
                return ResourceManager.GetString("SettingsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader extension flag 的本地化字符串。
        /// </summary>
        public static string Shader_extension_flag {
            get {
                return ResourceManager.GetString("Shader_extension_flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader extension version 的本地化字符串。
        /// </summary>
        public static string Shader_extension_version {
            get {
                return ResourceManager.GetString("Shader_extension_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size W/H 的本地化字符串。
        /// </summary>
        public static string Size_W_H {
            get {
                return ResourceManager.GetString("Size_W_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth 的本地化字符串。
        /// </summary>
        public static string Smooth {
            get {
                return ResourceManager.GetString("Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source X/Y/W/H 的本地化字符串。
        /// </summary>
        public static string Source_X_Y_W_H {
            get {
                return ResourceManager.GetString("Source_X_Y_W_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spine sprites 的本地化字符串。
        /// </summary>
        public static string Spine_sprites {
            get {
                return ResourceManager.GetString("Spine_sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprite 的本地化字符串。
        /// </summary>
        public static string Sprite {
            get {
                return ResourceManager.GetString("Sprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprites 的本地化字符串。
        /// </summary>
        public static string Sprites {
            get {
                return ResourceManager.GetString("Sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam AppID 的本地化字符串。
        /// </summary>
        public static string Steam_AppID {
            get {
                return ResourceManager.GetString("Steam_AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step 的本地化字符串。
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String - {0} 的本地化字符串。
        /// </summary>
        public static string String____0 {
            get {
                return ResourceManager.GetString("String____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string SType {
            get {
                return ResourceManager.GetString("SType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string SVersion {
            get {
                return ResourceManager.GetString("SVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap position 的本地化字符串。
        /// </summary>
        public static string Swap_position {
            get {
                return ResourceManager.GetString("Swap_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target X/Y/W/H 的本地化字符串。
        /// </summary>
        public static string Target_X_Y_W_H {
            get {
                return ResourceManager.GetString("Target_X_Y_W_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture 的本地化字符串。
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture group information - {0} 的本地化字符串。
        /// </summary>
        public static string Texture_group_information____0 {
            get {
                return ResourceManager.GetString("Texture_group_information____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture page item - {0} 的本地化字符串。
        /// </summary>
        public static string Texture_page_item____0 {
            get {
                return ResourceManager.GetString("Texture_page_item____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textures 的本地化字符串。
        /// </summary>
        public static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thank you for donation! 的本地化字符串。
        /// </summary>
        public static string Thank_you_for_donation {
            get {
                return ResourceManager.GetString("Thank_you_for_donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme: 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Columns 的本地化字符串。
        /// </summary>
        public static string Tile_Columns {
            get {
                return ResourceManager.GetString("Tile_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Count 的本地化字符串。
        /// </summary>
        public static string Tile_Count {
            get {
                return ResourceManager.GetString("Tile_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Height 的本地化字符串。
        /// </summary>
        public static string Tile_Height {
            get {
                return ResourceManager.GetString("Tile_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile ID 的本地化字符串。
        /// </summary>
        public static string Tile_ID {
            get {
                return ResourceManager.GetString("Tile_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile IDs 的本地化字符串。
        /// </summary>
        public static string Tile_IDs {
            get {
                return ResourceManager.GetString("Tile_IDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Width 的本地化字符串。
        /// </summary>
        public static string Tile_Width {
            get {
                return ResourceManager.GetString("Tile_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tilesets 的本地化字符串。
        /// </summary>
        public static string Tilesets {
            get {
                return ResourceManager.GetString("Tilesets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timestamp 的本地化字符串。
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QiuUTMTv4 - Qiuming 的本地化字符串。
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        public static string ToolText {
            get {
                return ResourceManager.GetString("ToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform else into continue 的本地化字符串。
        /// </summary>
        public static string Transform_else_into_continue {
            get {
                return ResourceManager.GetString("Transform_else_into_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparent 的本地化字符串。
        /// </summary>
        public static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try/catch/finally rewriting 的本地化字符串。
        /// </summary>
        public static string Try_catch_finally_rewriting {
            get {
                return ResourceManager.GetString("Try_catch_finally_rewriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio group - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleAudioGroupViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleAudioGroupViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleBackgroundViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleBackgroundViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleFontViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleFontViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path - {0} 的本地化字符串。
        /// </summary>
        public static string UndertalePathViewModelHeading {
            get {
                return ResourceManager.GetString("UndertalePathViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleScriptViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleScriptViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleShaderViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleShaderViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sound - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleSoundViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleSoundViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprite - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleSpriteViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleSpriteViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (UndertaleString reference) 的本地化字符串。
        /// </summary>
        public static string UndertaleString_reference {
            get {
                return ResourceManager.GetString("UndertaleString_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeline - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleTimelineViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleTimelineViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Always 2 的本地化字符串。
        /// </summary>
        public static string Unknown_Always_2 {
            get {
                return ResourceManager.GetString("Unknown_Always_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use CSS hex color literals 的本地化字符串。
        /// </summary>
        public static string Use_CSS_hex_color_literals {
            get {
                return ResourceManager.GetString("Use_CSS_hex_color_literals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use QiuUTMTv3 Script Engine to execute scripts (recommend, only work on Android) 的本地化字符串。
        /// </summary>
        public static string Use_QiuUTMTv3_Script_Engine_to_execute {
            get {
                return ResourceManager.GetString("Use_QiuUTMTv3_Script_Engine_to_execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Interface 的本地化字符串。
        /// </summary>
        public static string User_Interface {
            get {
                return ResourceManager.GetString("User_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable - {0} 的本地化字符串。
        /// </summary>
        public static string Variable____0 {
            get {
                return ResourceManager.GetString("Variable____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VarID 的本地化字符串。
        /// </summary>
        public static string VarID {
            get {
                return ResourceManager.GetString("VarID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertex sync 的本地化字符串。
        /// </summary>
        public static string Vertex_sync {
            get {
                return ResourceManager.GetString("Vertex_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WAV data, length:  的本地化字符串。
        /// </summary>
        public static string WAV_data__length {
            get {
                return ResourceManager.GetString("WAV_data__length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome! 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Qiuming&apos;s special version of Undertale Mod Tool !\n\n This project is developed based on many projects. Please refer to the about interface and source code for details.  Bilibili:@秋冥散雨_GenOuka 的本地化字符串。
        /// </summary>
        public static string Welcome_to_Qiumen_s_special_version {
            get {
                return ResourceManager.GetString("Welcome_to_Qiumen_s_special_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window color 的本地化字符串。
        /// </summary>
        public static string Window_color {
            get {
                return ResourceManager.GetString("Window_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
