//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UndertaleModToolAvalonia.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UndertaleModToolAvalonia.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Detect 的本地化字符串。
        /// </summary>
        public static string Auto_Detect {
            get {
                return ResourceManager.GetString("Auto_Detect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilibili… 的本地化字符串。
        /// </summary>
        public static string BilibiliText {
            get {
                return ResourceManager.GetString("BilibiliText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a script to run… 的本地化字符串。
        /// </summary>
        public static string ChooseScriptToRunText {
            get {
                return ResourceManager.GetString("ChooseScriptToRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string CloseFileText {
            get {
                return ResourceManager.GetString("CloseFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Tab 的本地化字符串。
        /// </summary>
        public static string CloseTabText {
            get {
                return ResourceManager.GetString("CloseTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code - {0} 的本地化字符串。
        /// </summary>
        public static string Code____0 {
            get {
                return ResourceManager.GetString("Code____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code locals - {0} 的本地化字符串。
        /// </summary>
        public static string Code_locals____0 {
            get {
                return ResourceManager.GetString("Code_locals____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string DonateText {
            get {
                return ResourceManager.GetString("DonateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded audio - {0} 的本地化字符串。
        /// </summary>
        public static string Embedded_audio____0 {
            get {
                return ResourceManager.GetString("Embedded_audio____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded image - {0} 的本地化字符串。
        /// </summary>
        public static string Embedded_image____0 {
            get {
                return ResourceManager.GetString("Embedded_image____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded texture - {0} 的本地化字符串。
        /// </summary>
        public static string Embedded_texture____0 {
            get {
                return ResourceManager.GetString("Embedded_texture____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension - {0}} 的本地化字符串。
        /// </summary>
        public static string Extension____0 {
            get {
                return ResourceManager.GetString("Extension____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string FileText {
            get {
                return ResourceManager.GetString("FileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by name… 的本地化字符串。
        /// </summary>
        public static string FilterByCodeText {
            get {
                return ResourceManager.GetString("FilterByCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function - {0} 的本地化字符串。
        /// </summary>
        public static string Function____0 {
            get {
                return ResourceManager.GetString("Function____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game object - {0} 的本地化字符串。
        /// </summary>
        public static string Game_object____0 {
            get {
                return ResourceManager.GetString("Game_object____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game End Scripts 的本地化字符串。
        /// </summary>
        public static string GameEndScriptsHeading {
            get {
                return ResourceManager.GetString("GameEndScriptsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Info 的本地化字符串。
        /// </summary>
        public static string GeneralInfoTabHeading {
            get {
                return ResourceManager.GetString("GeneralInfoTabHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github… 的本地化字符串。
        /// </summary>
        public static string GithubText {
            get {
                return ResourceManager.GetString("GithubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Init Scripts 的本地化字符串。
        /// </summary>
        public static string GlobalInitScriptsHeading {
            get {
                return ResourceManager.GetString("GlobalInitScriptsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inner Script 的本地化字符串。
        /// </summary>
        public static string InnerScriptText {
            get {
                return ResourceManager.GetString("InnerScriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🌏Language (Restart to apply) 的本地化字符串。
        /// </summary>
        public static string Language__Restart_to_apply {
            get {
                return ResourceManager.GetString("Language__Restart_to_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string NewFileText {
            get {
                return ResourceManager.GetString("NewFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string OpenFileText {
            get {
                return ResourceManager.GetString("OpenFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Particle system - {0} 的本地化字符串。
        /// </summary>
        public static string Particle_system____0 {
            get {
                return ResourceManager.GetString("Particle_system____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Particle system emitter - {0} 的本地化字符串。
        /// </summary>
        public static string Particle_system_emitter____0 {
            get {
                return ResourceManager.GetString("Particle_system_emitter____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ Group… 的本地化字符串。
        /// </summary>
        public static string QQGroupText {
            get {
                return ResourceManager.GetString("QQGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string QuitText {
            get {
                return ResourceManager.GetString("QuitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Room - {0} 的本地化字符串。
        /// </summary>
        public static string Room____0 {
            get {
                return ResourceManager.GetString("Room____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string SaveFileText {
            get {
                return ResourceManager.GetString("SaveFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script 的本地化字符串。
        /// </summary>
        public static string ScriptText {
            get {
                return ResourceManager.GetString("ScriptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Code 的本地化字符串。
        /// </summary>
        public static string SearchCodeText {
            get {
                return ResourceManager.GetString("SearchCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search In Code 的本地化字符串。
        /// </summary>
        public static string SearchInCodeHeading {
            get {
                return ResourceManager.GetString("SearchInCodeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsHeading {
            get {
                return ResourceManager.GetString("SettingsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String - {0} 的本地化字符串。
        /// </summary>
        public static string String____0 {
            get {
                return ResourceManager.GetString("String____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture group information - {0} 的本地化字符串。
        /// </summary>
        public static string Texture_group_information____0 {
            get {
                return ResourceManager.GetString("Texture_group_information____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Texture page item - {0} 的本地化字符串。
        /// </summary>
        public static string Texture_page_item____0 {
            get {
                return ResourceManager.GetString("Texture_page_item____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QiuUTMTv4 - Qiuming 的本地化字符串。
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tool 的本地化字符串。
        /// </summary>
        public static string ToolText {
            get {
                return ResourceManager.GetString("ToolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio group - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleAudioGroupViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleAudioGroupViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleBackgroundViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleBackgroundViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleFontViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleFontViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path - {0} 的本地化字符串。
        /// </summary>
        public static string UndertalePathViewModelHeading {
            get {
                return ResourceManager.GetString("UndertalePathViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleScriptViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleScriptViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shader - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleShaderViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleShaderViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sound - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleSoundViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleSoundViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprite - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleSpriteViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleSpriteViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeline - {0} 的本地化字符串。
        /// </summary>
        public static string UndertaleTimelineViewModelHeading {
            get {
                return ResourceManager.GetString("UndertaleTimelineViewModelHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable - {0} 的本地化字符串。
        /// </summary>
        public static string Variable____0 {
            get {
                return ResourceManager.GetString("Variable____0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
